apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: staging-star-rebble-io
  namespace: default
spec:
  dnsNames:
  - '*.rebble.io'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: staging-star-rebble-io
status: {}
