apiVersion: v1
kind: Secret
metadata:
  name: timeline-postgres
type: Opaque
stringData:
  url: postgres://timeline:timeline@postgres/timeline
---
apiVersion: v1
kind: Secret
metadata:
  name: appstore-postgres
type: Opaque
stringData:
  url: postgres://appstore:appstore@postgres/appstore
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres
type: Opaque
stringData:
  url: postgres://auth:auth@postgres/auth
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-facebook
type: Opaque
stringData:
  key: nope
  secret: nope
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-github
type: Opaque
stringData:
  key: nope
  secret: nope
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-google
type: Opaque
stringData:
  key: nope
  secret: nope
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-pebble
type: Opaque
stringData:
  key: nope
  secret: nope
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-twitter
type: Opaque
stringData:
  key: nope
  secret: nope
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret-key
type: Opaque
stringData:
  key: auth-not-very-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
stringData:
  key: not-very-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
stringData:
  public_key: nope
  secret_key: nope
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
type: Opaque
stringData:
  url: ""

