apiVersion: apps/v1
kind: Deployment
metadata:
  name: appstore-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohorts
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lp
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-app-icons
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-sync
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
