apiVersion: apps/v1
kind: Deployment
metadata:
  name: appstore-api
  labels:
    app: appstore-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appstore-api
  template:
    metadata:
      labels:
        app: appstore-api
    spec:
      containers:
        - name: appstore-api
          image: gcr.io/pebble-rebirth/appstore-api:g0e132e8
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: key
            - name: ALGOLIA_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: algolia
                  key: admin-api-key
            - name: ALGOLIA_APP_ID
              valueFrom:
                secretKeyRef:
                  name: algolia
                  key: app-id
            - name: ALGOLIA_INDEX
              valueFrom:
                secretKeyRef:
                  name: algolia
                  key: index
            - name: APPSTORE_ROOT
              value: https://apps.rebble.io
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: appstore-postgres
                  key: url
            - name: IMAGE_ROOT
              value: https://assets.rebble.io
            - name: PBW_ROOT
              value: https://pbws.rebble.io/pbw
            - name: REBBLE_AUTH_URL
              value: http://auth:8080
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: key
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: appstore-api
spec:
  selector:
    app: appstore-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
