apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr
  labels:
    app: asr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asr
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
        - name: asr
          image: gcr.io/pebble-rebirth/asr@sha256:d2a9b45218e9cbadb1bf6b4c2595934484ea5619c5e75a327d33b0ae732776a0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: key
            - name: SPEECH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-asr
                  key: key
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: asr
spec:
  selector:
    app: asr
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
