apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot
  labels:
    app: boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot
    spec:
      containers:
        - name: boot
          image: gcr.io/pebble-rebirth/boot:ged550da
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: APPSTORE_API_URL
              value: https://appstore-api.rebble.io
            - name: APPSTORE_API_LOCKER_URL
              value: https://ios-appstore-api.rebble.io
            - name: APPSTORE_URL
              value: https://apps.rebble.io
            - name: ASR_ROOT
              value: asr.rebble.io
            - name: COHORTS_URL
              value: https://cohorts.rebble.io
            - name: DOMAIN_ROOT
              value: rebble.io
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: key
            - name: LANGUAGE_PACK_URL
              value: https://lp.rebble.io
            - name: REBBLE_AUTH_URL
              value: https://auth.rebble.io
            - name: REBBLE_AUTH_INT_URL
              value: "http://auth:8080"
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: REBBLE_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: rebble-consumer
                  key: key
            - name: REBBLE_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: rebble-consumer
                  key: secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: key
            - name: WEATHER_URL
              value: https://weather.rebble.io
            - name: WS_PROXY_URL
              value: wss://dev-ws-proxy.rebble.io/device
          resources:
            limits:
              cpu: 100m
              memory: 96Mi
            requests:
              cpu: 20m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: boot
spec:
  selector:
    app: boot
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
