apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-sync
  labels:
    app: timeline-sync
spec:
  replicas: 4
  selector:
    matchLabels:
      app: timeline-sync
  template:
    metadata:
      labels:
        app: timeline-sync
    spec:
      containers:
        - name: timeline-sync
          image: gcr.io/pebble-rebirth/timeline-sync:gec26250
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: REBBLE_AUTH_URL
            value: "http://auth:8080"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: url_timeline
          - name: DOMAIN_ROOT
            value: rebble.io
          - name: HONEYCOMB_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb
                key: key
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-key
                key: key
          - name: SERVER_NAME
            value: timeline-sync.rebble.io
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: timeline-sync
spec:
  selector:
    app: timeline-sync
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
