apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: star-rebble-io
  namespace: default
spec:
  secretName: star-rebble-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.rebble.io"
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: star-asr-rebble-io
  namespace: default
spec:
  secretName: star-asr-rebble-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.asr.rebble.io"
