apiVersion: apps/v1
kind: Deployment
metadata:
  name: appstore-api
  labels:
    app: appstore-api
spec:
  replicas: 12
  selector:
    matchLabels:
      app: appstore-api
  template:
    metadata:
      labels:
        app: appstore-api
    spec:
      containers:
        - name: appstore-api
          image: gcr.io/pebble-rebirth/appstore-api:g21a464d
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: HONEYCOMB_WRITEKEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: key
            - name: HONEYCOMB_DATASET
              value: rws
            - name: ALGOLIA_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: algolia
                  key: admin-api-key
            - name: ALGOLIA_APP_ID
              valueFrom:
                secretKeyRef:
                  name: algolia
                  key: app-id
            - name: ALGOLIA_INDEX
              valueFrom:
                secretKeyRef:
                  name: algolia
                  key: index
            - name: APPSTORE_ROOT
              value: https://apps.rebble.io
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: appstore-postgres
                  key: url
            - name: IMAGE_ROOT
              value: https://assets2.rebble.io
            - name: PBW_ROOT
              value: https://storage.googleapis.com/rebble-pbws/pbw
            - name: REBBLE_AUTH_URL
              value: http://auth:8080
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: key
            - name: DISCORD_HOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord
                  key: appstore-webhook
            - name: DISCORD_ADMIN_HOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord
                  key: appstore-admin-webhook
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gcp-s3-appstore-api
                  key: accesskey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gcp-s3-appstore-api
                  key: secretkey
            - name: S3_ENDPOINT
              value: https://storage.googleapis.com
            - name: TEST_APP_UUID
              value: db9af49b-065a-442c-8042-08b812317de4
            - name: DISCOURSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: discourse-bot-key
                  key: key
            - name: DISCOURSE_USER
              value: anne_droid
            - name: DISCOURSE_SHOWCASE_TOPIC_ID
              value: "3"
          resources:
            limits:
              cpu: 200m
              memory: 224Mi
            requests:
              cpu: 100m
              memory: 192Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: appstore-api
spec:
  selector:
    app: appstore-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
