apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobby
  labels:
    app: bobby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bobby
  template:
    metadata:
      labels:
        app: bobby
    spec:
      containers:
        - name: bobby
          image: gcr.io/pebble-rebirth/bobby-service:v0.0.16
          ports:
            - containerPort: 8080
          env:
          - name: IBM_KEY
            valueFrom:
              secretKeyRef:
                name: ibm-weather-api-v2
                key: key
          - name: HONEYCOMB_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb
                key: key
          - name: MAPBOX_KEY
            valueFrom:
              secretKeyRef:
                name: mapbox
                key: key
          - name: USER_IDENTIFICATION_URL
            value: http://user-identifier:8080/api/v1/token_info
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URL
            value: redis://:$(REDIS_PASS)@redis/1
          - name: OPENAI_KEY
            valueFrom:
              secretKeyRef:
                name: openai
                key: key
          - name: OPENAI_ORG
            valueFrom:
              secretKeyRef:
                name: openai
                key: org
          - name: HERE_KEY
            valueFrom:
              secretKeyRef:
                name: here
                key: key
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 96Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bobby-backend-config
spec:
  timeoutSec: 120
---
apiVersion: v1
kind: Service
metadata:
  name: bobby
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080": "bobby-backend-config"}}'
spec:
  selector:
    app: bobby
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
