apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohorts
  labels:
    app: cohorts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cohorts
  template:
    metadata:
      labels:
        app: cohorts
    spec:
      containers:
        - name: cohorts
          image: gcr.io/pebble-rebirth/cohorts:geeed007
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: APPSTORE_API_URL
              value: https://appstore-api.rebble.io
            - name: APPSTORE_URL
              value: https://apps.rebble.io
            - name: ASR_ROOT
              value: asr.rebble.io
            - name: COHORTS_URL
              value: https://cohorts.rebble.io
            - name: DOMAIN_ROOT
              value: rebble.io
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: key
            - name: LANGUAGE_PACK_URL
              value: https://lp.rebble.io
            - name: REBBLE_AUTH
              value: "http://auth:8080"
            - name: REBBLE_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: rebble-consumer
                  key: key
            - name: REBBLE_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: rebble-consumer
                  key: secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: key
            - name: WEATHER_URL
              value: https://weather.rebble.io
          resources:
            limits:
              cpu: 50m
              memory: 96Mi
            requests:
              cpu: 25m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cohorts
spec:
  selector:
    app: cohorts
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
