apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-persist
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis-persist
  template:
    metadata:
      labels:
        app: redis-persist
    spec:
      containers:
        - name: redis
          image: redis:7.0
          args:
            - --requirepass
            - $(REDIS_PASS)
            - --dir
            - /redis-data/
            - --appendonly
            - "yes"
            - --auto-aof-rewrite-percentage
            - "100"
            - --auto-aof-rewrite-min-size
            - 64mb
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: redis
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - name: redis-storage
              mountPath: /redis-data
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis-persist
