apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  creationTimestamp: null
  name: letsencrypt-prod
spec:
  acme:
    email: katharine@kathar.in
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: pebble-rebirth
status: {}
