apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: null
    name: star-rebble-io
    namespace: default
  spec:
    dnsNames:
    - '*.rebble.io'
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: star-rebble-io
  status: {}
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: null
    name: star-asr-rebble-io
    namespace: default
  spec:
    dnsNames:
    - '*.asr.rebble.io'
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: star-asr-rebble-io
  status: {}
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: star-asr-test-rebble-io
    namespace: default
  spec:
    dnsNames:
    - '*.asr-test.rebble.io'
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: star-asr-test-rebble-io
kind: List
