apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohorts
  labels:
    app: cohorts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cohorts
  template:
    metadata:
      labels:
        app: cohorts
    spec:
      containers:
        - name: cohorts
          image: gcr.io/pebble-rebirth/cohorts
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SCRIPT_NAME
              valueFrom:
                configMapKeyRef:
                  name: script-names
                  key: cohorts
                  optional: true
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: key
                  optional: true
            - name: REBBLE_AUTH
              value: http://auth:8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 40m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /cohorts/heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /cohorts/heartbeat
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cohorts
spec:
  selector:
    app: cohorts
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
