apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ws-proxy
  labels:
    app: ws-proxy
spec:
  replicas: 1
  serviceName: ws-proxy
  selector:
    matchLabels:
      app: ws-proxy
  template:
    metadata:
      labels:
        app: ws-proxy
    spec:
      containers:
        - name: ws-proxy
          image: gcr.io/pebble-rebirth/dev-ws-proxy
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: PEBBLE_AUTH_URL
            value: "http://auth:8080"
          - name: HONEYCOMB_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb
                key: key
                optional: true
          - name: PING_INTERVAL_SECONDS
            value: "60"
          - name: PING_TIMEOUT_SECONDS
            value: "240"
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ws-proxy
spec:
  selector:
    app: ws-proxy
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
