apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: staging-star-rebble-io
  namespace: default
spec:
  secretName: staging-star-rebble-io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - "*.rebble.io"
